/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatMessageRenderer: typeof import('./components/ChatMessageRenderer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PageSwiper: typeof import('./components/PageSwiper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionScroller: typeof import('./components/SectionScroller.vue')['default']
    SwipeContainerDemo: typeof import('./components/SwipeContainerDemo.vue')['default']
  }
}
